### ISSUE TITLE
The TinyPNG option should not exist for incompatible files

### ISSUE THREAD

**Issue by kanlukasz** [andi1984/vscode-tinypng#8]
If you right-click the tab, you'll see the TinyPNG option. But wait ... it's a PHP file, so we can't use TinyPNG for it. Logically, it shouldn't be there

![obraz](https://user-images.githubusercontent.com/30685349/76142026-e2230580-6069-11ea-9f74-6b22a1f10021.png)

The same for other tabs like:
![obraz](https://user-images.githubusercontent.com/30685349/76142053-362dea00-606a-11ea-8012-65d268807618.png)

or
![obraz](https://user-images.githubusercontent.com/30685349/76142055-3e862500-606a-11ea-8c66-122b30651c21.png)

**Comment by andi1984** [comment]
Hi @kanlukasz,

that is very weird, because this context menu entry on a file should follow this rule:

https://github.com/andi1984/vscode-tinypng/blob/master/package.json#L80

and thus should only appear on png and jp(e)g files. I tried to reproduce this myself on a PHP file, but I can not see it here (Windows machine). I will try later again on a mac.

In the meantime: Can you check that you are on the latest version 0.3.0 of this extension? So either this `when` clause is not taken into account at all from your VSCode version (which one is it?) or the file itself represents itself as an image file to VSCode in some way to fullfill this clause.

**Comment by kanlukasz** [comment]
Hi, sorry for the lack of information about the environment.
**My OS:** Win10 1909
**It was reproduced on VSCode** 1.42.1

Hmm Ok, that's weird, but maybe let's do it again together:

Step 1 - Install clean latest release VS Code (eg. portable), but not Insider version
Step 2 - Install your plugin
Step 3 - Check issue

GIF Screencast:
![stream](https://user-images.githubusercontent.com/30685349/76205129-eb42dc80-61f9-11ea-8e72-b125ce43df8a.gif)

**Comment by andi1984** [comment]
@kanlukasz I figured out the issue and updated the extension to v0.3.1. Can you check whether the bug is still there in that particular version? Otherwise we can close this issue.

Thx again for spotting this issue.

**Comment by kanlukasz** [comment]
Yes, it's ok now :) Thx
